In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

def f_hook(m, i, o):
    print(m)
    print(type(m))
    print("forward_input")
    print(type(i))
    for a in i:
        print(a)
    print("forward_output")
    print(type(o))
    print(o)
    print()

def b_hook(m, i, o):
    print(m)
    print(type(m))
    print("grad_input")
    print(type(i))
    for a in i:
        print(a)
    print("grad_output")
    print(type(o))
    for a in o:
        print(a)
    print()

def tensor_hook(x):
    print(type(x))
    print(x)
    print()

## Linear

(grad_bias, grad_in, grad_weight)

In [28]:
x = torch.rand(1, 5)
linear_layer = nn.Linear(5, 3)
relu = nn.ReLU()
linear_layer2 = nn.Linear(3, 2)

linear_layer.register_forward_hook(f_hook)
relu.register_forward_hook(f_hook)
linear_layer2.register_forward_hook(f_hook)
linear_layer.register_backward_hook(b_hook)
relu.register_backward_hook(b_hook)
linear_layer2.register_backward_hook(b_hook)
o1 = linear_layer(x)
o2 = relu(o1)
o3 = linear_layer2(o2)
o4 = 9 - o3.mean()

Linear(in_features=5, out_features=3, bias=True)
<class 'torch.nn.modules.linear.Linear'>
forward_input
<class 'tuple'>
tensor([[0.1166, 0.3608, 0.2607, 0.3822, 0.2083]])
forward_output
<class 'torch.Tensor'>
tensor([[ 0.4286,  0.5460, -0.2543]], grad_fn=<AddmmBackward>)

ReLU()
<class 'torch.nn.modules.activation.ReLU'>
forward_input
<class 'tuple'>
tensor([[ 0.4286,  0.5460, -0.2543]], grad_fn=<AddmmBackward>)
forward_output
<class 'torch.Tensor'>
tensor([[0.4286, 0.5460, 0.0000]], grad_fn=<ReluBackward0>)

Linear(in_features=3, out_features=2, bias=True)
<class 'torch.nn.modules.linear.Linear'>
forward_input
<class 'tuple'>
tensor([[0.4286, 0.5460, 0.0000]], grad_fn=<ReluBackward0>)
forward_output
<class 'torch.Tensor'>
tensor([[0.6585, 0.4959]], grad_fn=<AddmmBackward>)



In [27]:
o4.backward()

Linear(in_features=3, out_features=2, bias=True)
<class 'torch.nn.modules.linear.Linear'>
grad_input
<class 'tuple'>
tensor([-0.5000, -0.5000])
tensor([[-0.0240,  0.1448,  0.4023]])
tensor([[-0.1754, -0.1754],
        [-0.0000, -0.0000],
        [-0.0000, -0.0000]])
grad_output
<class 'tuple'>
tensor([[-0.5000, -0.5000]])

ReLU()
<class 'torch.nn.modules.activation.ReLU'>
grad_input
<class 'tuple'>
tensor([[-0.0240,  0.0000,  0.0000]])
grad_output
<class 'tuple'>
tensor([[-0.0240,  0.1448,  0.4023]])

Linear(in_features=5, out_features=3, bias=True)
<class 'torch.nn.modules.linear.Linear'>
grad_input
<class 'tuple'>
tensor([-0.0240,  0.0000,  0.0000])
None
tensor([[-0.0132,  0.0000,  0.0000],
        [-0.0025,  0.0000,  0.0000],
        [-0.0111,  0.0000,  0.0000],
        [-0.0156,  0.0000,  0.0000],
        [-0.0223,  0.0000,  0.0000]])
grad_output
<class 'tuple'>
tensor([[-0.0240,  0.0000,  0.0000]])



## Conv2d

In [4]:
x = torch.randn(1, 1, 5, 5)
conv_layer = nn.Conv2d(1, 1, 2, 1)
relu = nn.ReLU()
conv_layer2 = nn.Conv2d(1, 1, 2, 1)

conv_layer.register_forward_hook(f_hook)
relu.register_forward_hook(f_hook)
conv_layer2.register_forward_hook(f_hook)
conv_layer.register_backward_hook(b_hook)
relu.register_backward_hook(b_hook)
conv_layer2.register_backward_hook(b_hook)
o1 = conv_layer(x)
o2 = relu(o1)
o3 = conv_layer2(o2)
o4 = 1 - o3.mean()

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1))
<class 'torch.nn.modules.conv.Conv2d'>
forward_input
<class 'tuple'>
tensor([[[[ 1.2836, -0.2270, -0.9304,  1.9135,  0.4740],
          [-0.1847,  0.7955, -1.7954, -1.6828,  0.1623],
          [ 1.0666,  0.0740, -0.9193, -1.6213,  0.6768],
          [ 0.5157,  0.8056,  1.3990,  0.9471,  0.6415],
          [ 1.5605, -0.7896,  0.5739,  0.9425,  0.9377]]]])
forward_output
<class 'torch.Tensor'>
tensor([[[[ 0.2494,  0.8201, -1.5967, -0.3210],
          [ 0.0987,  0.9743, -0.4406, -1.7222],
          [ 0.4103,  0.3458,  0.5352, -0.6002],
          [ 0.7747, -0.6839,  0.2814,  0.3738]]]],
       grad_fn=<ThnnConv2DBackward>)

ReLU()
<class 'torch.nn.modules.activation.ReLU'>
forward_input
<class 'tuple'>
tensor([[[[ 0.2494,  0.8201, -1.5967, -0.3210],
          [ 0.0987,  0.9743, -0.4406, -1.7222],
          [ 0.4103,  0.3458,  0.5352, -0.6002],
          [ 0.7747, -0.6839,  0.2814,  0.3738]]]],
       grad_fn=<ThnnConv2DBackward>)
forward_outp

In [5]:
o4.backward()

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1))
<class 'torch.nn.modules.conv.Conv2d'>
grad_input
<class 'tuple'>
tensor([[[[0.0055, 0.0216, 0.0216, 0.0161],
          [0.0587, 0.1119, 0.1119, 0.0533],
          [0.0587, 0.1119, 0.1119, 0.0533],
          [0.0532, 0.0904, 0.0904, 0.0372]]]])
tensor([[[[-0.3815, -0.2973],
          [-0.3800, -0.2789]]]])
tensor([-1.])
grad_output
<class 'tuple'>
tensor([[[[-0.1111, -0.1111, -0.1111],
          [-0.1111, -0.1111, -0.1111],
          [-0.1111, -0.1111, -0.1111]]]])

ReLU()
<class 'torch.nn.modules.activation.ReLU'>
grad_input
<class 'tuple'>
tensor([[[[0.0055, 0.0216, 0.0000, 0.0000],
          [0.0587, 0.1119, 0.0000, 0.0000],
          [0.0587, 0.1119, 0.1119, 0.0000],
          [0.0532, 0.0000, 0.0904, 0.0372]]]])
grad_output
<class 'tuple'>
tensor([[[[0.0055, 0.0216, 0.0216, 0.0161],
          [0.0587, 0.1119, 0.1119, 0.0533],
          [0.0587, 0.1119, 0.1119, 0.0533],
          [0.0532, 0.0904, 0.0904, 0.0372]]]])

Conv2d(1, 1, kern

## MaxPool2d

In [9]:
x = torch.randn(1, 1, 8, 8).requires_grad_(True)
pool_layer = nn.MaxPool2d(2)
relu = nn.ReLU()
pool_layer2 = nn.MaxPool2d(2)

pool_layer.register_forward_hook(f_hook)
relu.register_forward_hook(f_hook)
pool_layer2.register_forward_hook(f_hook)
pool_layer.register_backward_hook(b_hook)
relu.register_backward_hook(b_hook)
pool_layer2.register_backward_hook(b_hook)
o1 = pool_layer(x)
o2 = relu(o1)
o3 = pool_layer2(o2)
o4 = 1 - o3.mean()

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
<class 'torch.nn.modules.pooling.MaxPool2d'>
forward_input
<class 'tuple'>
tensor([[[[ 0.2773,  0.3788, -0.8474,  1.6525, -1.4269, -0.1751, -0.7948,
            0.2649],
          [-0.5877,  1.7464,  0.4918, -1.7818,  0.0117, -1.9523, -1.2985,
           -0.9928],
          [-0.0988, -0.1853,  0.1200,  1.1873,  0.8811, -2.5908, -0.8597,
            2.3402],
          [ 0.1572, -0.2378,  0.3196,  0.0429, -0.1465,  0.7755, -0.3924,
           -0.3190],
          [ 0.0209, -0.5632, -1.1840,  0.2455,  1.0940, -0.0181, -0.2725,
            2.7206],
          [ 0.0907, -0.2583,  1.3619,  0.2521,  0.7138,  0.7075, -0.9619,
            0.6584],
          [-0.4279, -1.5434, -0.6213, -1.6734,  0.4150,  0.1512, -0.0308,
           -1.2621],
          [-1.4041,  1.6359,  0.2737, -1.0433,  0.1063,  1.4708,  1.3754,
            0.1227]]]], requires_grad=True)
forward_output
<class 'torch.Tensor'>
tensor([[[[1.7464, 1.6525, 0.

In [10]:
o4.backward()

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
<class 'torch.nn.modules.pooling.MaxPool2d'>
grad_input
<class 'tuple'>
tensor([[[[-0.2500,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [-0.2500,  0.0000,  0.0000,  0.0000]]]])
grad_output
<class 'tuple'>
tensor([[[[-0.2500, -0.2500],
          [-0.2500, -0.2500]]]])

ReLU()
<class 'torch.nn.modules.activation.ReLU'>
grad_input
<class 'tuple'>
tensor([[[[-0.2500,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [-0.2500,  0.0000,  0.0000,  0.0000]]]])
grad_output
<class 'tuple'>
tensor([[[[-0.2500,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [ 0.0000,  0.0000,  0.0000, -0.2500],
          [-0.2500,  0.0000,  0.0000,  0.0000]]]])

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=Fa

## RNN

In [4]:
torch.manual_seed(5)
x = torch.randn(1, 2, 5).requires_grad_(True)
rnn_layer = nn.RNN(5, 3, 1, batch_first=True)
softmax = nn.Softmax(dim=1)
 
rnn_layer.register_forward_hook(f_hook)
# softmax.register_forward_hook(f_hook)
rnn_layer.register_backward_hook(b_hook)
# softmax.register_backward_hook(b_hook)
rnn_layer.weight_hh_l0.register_hook(tensor_hook)
rnn_layer.weight_ih_l0.register_hook(tensor_hook)
o1, h1 = rnn_layer(x)
o2 = softmax(h1.squeeze(1))
grad = torch.FloatTensor([[1, 0, 0]])

RNN(5, 3, batch_first=True)
<class 'torch.nn.modules.rnn.RNN'>
forward_input
<class 'tuple'>
tensor([[[-0.4868, -0.6038, -0.5581,  0.6675, -0.1974],
         [ 1.9428, -1.4017, -0.7626,  0.6312, -0.8991]]], requires_grad=True)
forward_output
<class 'tuple'>
tensor([[[ 0.7737,  0.6712,  0.7200],
         [ 0.9293,  0.0850, -0.2211]]], grad_fn=<TransposeBackward1>)
tensor([[[ 0.9293,  0.0850, -0.2211]]], grad_fn=<StackBackward>)



In [5]:
l = F.cross_entropy(o1.view(-1, 3), torch.LongTensor([1, 0]))
l.backward()

RNN(5, 3, batch_first=True)
<class 'torch.nn.modules.rnn.RNN'>
grad_input
<class 'tuple'>
tensor([[[ 0.1754, -0.3417,  0.1662]],

        [[-0.2137,  0.1231,  0.0906]]])
grad_output
<class 'tuple'>
tensor([[[ 0.1754, -0.3417,  0.1662],
         [-0.2137,  0.1231,  0.0906]]])

<class 'torch.Tensor'>
tensor([[-0.0225, -0.0196, -0.0210],
        [ 0.0945,  0.0820,  0.0880],
        [ 0.0667,  0.0579,  0.0621]])
<class 'torch.Tensor'>
tensor([[-0.0849,  0.0058, -0.0101,  0.0203,  0.0148],
        [ 0.3266, -0.0606,  0.0091, -0.0452, -0.0737],
        [ 0.1169, -0.1835, -0.1237,  0.1238, -0.0980]])
